### PR TITLE
Added 'revert' parameter for CircularAnimation

### PR DESCRIPTION
**Pull request by NinjaRhyme**

### CODE REVIEW

**Comment by artemSydorenko** [comment]
By word "invert" I meant that it will cut view by inner side of circle instead of the outside. More correctly will be to add another an option parameter ("revert" for example) to the method and if it equal to true than swap startPath with endPath.

**Comment by maximletushov** [comment]
@artemSydorenko thanks.
@NinjaRhyme do you need 'revert' parameter as @artemSydorenko described ?

**Comment by NinjaRhyme** [comment]
Yep! What I need is 'revert' as @artemSydorenko described. Many thanks~

**Comment by NinjaRhyme** [comment]
Well, it's not a bug at all, so I rewrote the title.

**Comment by artemSydorenko** [comment]
Wow, looks good. Thanks @NinjaRhyme

**Pull request merged**
